#!/bin/bash

BOOKMARK_DIR="$HOME/.local/bookmarks"
BOOKMARK_FILE="$BOOKMARK_DIR/bookmarks.txt"

if [ ! -d $BOOKMARK_DIR ]; then
    mkdir -p $BOOKMARK_DIR;
fi

if [ ! -f $BOOKMARK_FILE ]; then
    /usr/bin/touch $BOOKMARK_FILE;
fi

selected_bookmark=$( \
    tac $BOOKMARK_FILE | \
    rofi -dmenu -p "  " \
    -mesg "Select Bookmarks" \
    -i -theme-str "window{width: 1000;} textbox{horizontal-align: 0.5;} listview{lines:12;columns:1;}" \
)
if [ "$selected_bookmark" = "" ]; then
    exit 0;
fi

if [ $(printf $selected_bookmark | grep -c '^\[') -gt 0 ]; then
    bookmark_url=$(echo -n $selected_bookmark | cut -d "]" -f2 | tr -d " ");
    xdotool type $bookmark_url;
else
    xdotool type $selected_bookmark;
fi

